version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7001:80
    volumes:
      - ./php:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - 5500:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1974
      - MYSQL_DATABASE=ktz
      - MYSQL_USER=ucid
      - MYSQL_PASSWORD=1974
    volumes:
      - ./mysql_data:/var/lib/mysql
